### ISSUE TITLE
mutations are supposed to be dashed uppercase

### ISSUE THREAD

**Issue by simonneutert** [simonneutert/fridgy#17]

**Comment by wieczo** [comment]
Man kann noch einen Schritt weiter gehen, als im Vue Workshop beschrieben: 

https://vuex.vuejs.org/guide/mutations.html#using-constants-for-mutation-types

Die uppercase Actions werden in einem Modul als `const` definiert und diese Konstanten als Methoden-Namen verwendet.

**Comment by phroggar** [comment]
Aber wenn man dem Credo folgt dass die Mutations eigentlich nur local genutzt werden sollten und alle anderen Actions verwenden macht das mit den Konstanten m.E. nicht soo viel Sinn oder?

**Comment by wieczo** [comment]
Ja, hast Recht. Das Mutation-Modul dient dazu näher an React zu sein.
