### ISSUE TITLE
Frontend startet nicht

### ISSUE THREAD

**Issue by wieczo** [simonneutert/fridgy#18]
Der Fehler tritt auf, wenn ich das Projekt mit `npm run dev` starte

1. git checkout fridgy
2. npm install
3. node src/server.js
4. npm run dev
5. Fehlermeldung in Konsole:

<pre>
> Starting dev server...
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.

 ERROR  Failed to compile with 10 errors                                                                                                                                           10:09:05 PM
 error  in ./node_modules/bootstrap-vue/dist/bootstrap-vue.css

Module build failed: ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
</pre>

6. Fehlermeldung im Browser:

> Cannot GET /

**Comment by wieczo** [comment]
Es ist durch aus möglich, dass der Fehler am 2. Punkt liegt:

> npm install

Sollte ich was anderes ausführen, um die `package-lock.json` Pakete einzuspielen?

**Comment by simonneutert** [comment]
`node_modules` Ordner löschen und dann nochmal `npm install` bei mir hier gibt es Probleme mit dem sqlite3 package :-/
